### ISSUE TITLE
EAT example fails..

### ISSUE THREAD

**Issue by BradWalker** [laurencelundblade/ctoken#43]
cotken passes all the tests..

[bwalker@localhost ctoken]$ ./ctoken_test
sizeof(ctoken_decode_context) 432
sizeof(ctoken_encode_ctx) 312
...
cwt_tags_test PASSED
get_next_test PASSED
SUMMARY: 18 tests run; 0 tests failed
[bwalker@localhost ctoken]$ 

But, the EAT test seems to fail.. Any idea why or where I should look to try and debug this?

[bwalker@localhost ctoken]$ ./eat_example_ossl
Made EC key with curve prime256v1: 0 (success)
Finished making EAT: 2 (fail)
[bwalker@localhost ctoken]$

**Comment by laurencelundblade** [comment]
I've pushed a fix for it. Somehow a line of code got lost in the examples (sorry). Thanks for filing the issue.
