### ISSUE TITLE
Help requested for compiling ctoken.

### ISSUE THREAD

**Issue by nayavij** [laurencelundblade/ctoken#57]
Hello,
I am trying to compile ctoken project. I did the changes in Makefile to point to my local versions  (latest masters ) of mbedtls / t_cose /QCBOR. But unfortunately, I ended up at below compilation issues ... 

cc -o ctoken_test main.o test/eat_test.o test/cwt_test.o test/psa_test.o test/run_tests.o test/eat_test_tokens.o libctoken.a ../QCBOR/build_dir/libqcbor.a ../t_cose/libt_cose.a ../mbedtls/build_dir/library/libmbedcrypto.a -lm 
cc -I ../mbedtls/include/ -I ../QCBOR/inc -I ../t_cose/inc -I inc -I test  -I src  -Os -fPIC     -c -o examples/eat_example_psa.o examples/eat_example_psa.c
In file included from ../mbedtls/include/psa/crypto.h:68,
                 from examples/eat_example_psa.c:35:
examples/eat_example_psa.c: In function ‘make_psa_ecdsa_key_pair’:
examples/eat_example_psa.c:120:57: error: ‘**PSA_ECC_CURVE_SECP256R1**’ undeclared (first use in this function)
  120 |             key_type        = PSA_KEY_TYPE_ECC_KEY_PAIR(PSA_ECC_CURVE_SECP256R1);
      |                                                         ^~~~~~~~~~~~~~~~~~~~~~~
../mbedtls/include/psa/crypto_values.h:524:40: note: in definition of macro ‘PSA_KEY_TYPE_ECC_KEY_PAIR’
  524 |     (PSA_KEY_TYPE_ECC_KEY_PAIR_BASE | (curve))
      |                                        ^~~~~
examples/eat_example_psa.c:120:57: note: each undeclared identifier is reported only once for each function it appears in
  120 |             key_type        = PSA_KEY_TYPE_ECC_KEY_PAIR(PSA_ECC_CURVE_SECP256R1);
      |                                                         ^~~~~~~~~~~~~~~~~~~~~~~
../mbedtls/include/psa/crypto_values.h:524:40: note: in definition of macro ‘PSA_KEY_TYPE_ECC_KEY_PAIR’
  524 |     (PSA_KEY_TYPE_ECC_KEY_PAIR_BASE | (curve))
      |                                        ^~~~~
examples/eat_example_psa.c:127:57: error: ‘**PSA_ECC_CURVE_SECP384R1**’ undeclared (first use in this function)
  127 |             key_type        = PSA_KEY_TYPE_ECC_KEY_PAIR(PSA_ECC_CURVE_SECP384R1);
      |                                                         ^~~~~~~~~~~~~~~~~~~~~~~
../mbedtls/include/psa/crypto_values.h:524:40: note: in definition of macro ‘PSA_KEY_TYPE_ECC_KEY_PAIR’
  524 |     (PSA_KEY_TYPE_ECC_KEY_PAIR_BASE | (curve))
      |                                        ^~~~~
examples/eat_example_psa.c:134:57: error: ‘**PSA_ECC_CURVE_SECP521R1**’ undeclared (first use in this function)
  134 |             key_type        = PSA_KEY_TYPE_ECC_KEY_PAIR(PSA_ECC_CURVE_SECP521R1);
      |                                                         ^~~~~~~~~~~~~~~~~~~~~~~
../mbedtls/include/psa/crypto_values.h:524:40: note: in definition of macro ‘PSA_KEY_TYPE_ECC_KEY_PAIR’
  524 |     (PSA_KEY_TYPE_ECC_KEY_PAIR_BASE | (curve))
      |                                        ^~~~~
make: *** [<builtin>: examples/eat_example_psa.o] Error 1

 I understand as curves for certain macros has been deprecated from here (https://armmbed.github.io/mbed-crypto/html/appendix/history.html). Has any one faced this problem , if so any light on how to sail through would be appreciated..

Thanks,
Vijay

**Comment by laurencelundblade** [comment]
Look here: https://github.com/laurencelundblade/t_cose/blob/master/examples/t_cose_basic_example_psa.c

It has the same function, but is fixed. 

Will try to fix ctoken in the next day or so also.

**Comment by laurencelundblade** [comment]
Fixed by #58

**Comment by nayavij** [comment]
Thanks
